version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: foodclub-api
    environment:
      NODE_ENV: production
      DATABASE_HOST: dpg-d11dmee3jp1c73cabolg-a
      DATABASE_PORT: 5432
      DATABASE_USER: foodclub_db_user
      DATABASE_NAME: foodclub_db
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}  # Será pego do arquivo .env
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  foodclub-network:
    driver: bridge

volumes:
  postgres_data: 